# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genre_name', models.CharField(max_length=100)),
                ('genre_type', models.CharField(max_length=500)),
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('track_name', models.CharField(max_length=500)),
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('singer', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.Genres')),
            ],
        ),
    ]
