# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='genre_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
